### ISSUE TITLE
Move  react app to NPM workspaces

### ISSUE THREAD

**Issue by niraj2477** [rtCamp/next-pms#344]
## **Description**
- For better maintainability and scalability, we have to refactor the next pms  react app into NPM workspaces.

## Tasks
- [x] Create a single package app. Namespace @next-pms
- [x] Create design-system package and move all the shared components.
- [x] Create hooks package and import in both app and design-system packages.
- [x] Refactor resource-management code to remove all Redux or Frappe React SDK.( It should consume data and provide hooks to update data.)
- [x] Create resource-management package and move this refactored code.
- [x] Refactor large files into smaller and re-usable component.

## **Additional Context**
- Package names will be
```
@next-pms/design-system
@next-pms/hooks
@next-pms/app
```
- [best practices](https://docs.google.com/document/d/16QKZf-PYjgqPY0daSZlnDsURJjrcF23Edf-q2JvuJuE/)
