### ISSUE TITLE
Employee search issues on the Homepage

### ISSUE THREAD

**Issue by KanchanChauhan** [rtCamp/next-pms#76]
- [ ] Search is slow, there is a refresh on search

<img width="1512" alt="Screenshot 2024-08-29 at 12 29 09 PM" src="https://github.com/user-attachments/assets/e6b86102-9b38-42da-8452-9d02b578d20e">

- [x] When you move to different page and come back, still the search result is there but nothing in filter.

<img width="803" alt="Screenshot 2024-08-29 at 12 30 55 PM" src="https://github.com/user-attachments/assets/99c82436-384a-4a16-8f27-4f68f4b20ced">

```[tasklist]
### Tasks
- [ ] Initial loading of team takes time
- [ ] Load more is refreshing entire list again and not pointing to newly loaded data
```
